- name: Install and configure snap in CentOS
  block:
  - name: Install EPEL packages
    yum:
      name: epel-release
      state: present

  - name: Install snapd using yum
    yum:
      name: snapd
      state: latest

  - name: Enable snap communication socket
    command: systemctl enable --now snapd.socket

  - name: Create a sym link if not exist
    file:
      src: /var/lib/snapd/snap
      dest: /snap
      state: link
  when: ansible_distribution == 'CentOS'

- name: Install Microk8s
  community.general.snap:
    name: microk8s
    state: present
    classic: yes
