---
- name: Get microk8s cluster joining link from master node
  hosts: localhost
  gather_facts: no
  tasks:

  - name: >
      Get the command to join.
      Create a new token for an hour
    shell: "microk8s add-node --token-ttl 3600 | awk 'NR==2'"
    register: run_from_worker

  - name: Set fact for the command
    set_fact:
      become_a_node_command: "{{ run_from_worker.stdout }}"

- name: Install microk8s on linux
  hosts: linux
  become: yes
  roles:
  - minion
...
