---
- name: Get microk8s cluster joining link from control plane node
  hosts: localhost
  gather_facts: no
  roles:
  - control-plane

- name: Install microk8s on linux
  hosts: linux
  become: yes
  roles:
  - minion
...
