- name: Get microk8s cluster joining link from control plane node
  hosts: localhost
  roles:
  - node-microk8s
  - control-plane-microk8s

- name: Install microk8s on linux
  hosts: linux
  become: yes
  roles:
  - node-microk8s
  - worker-microk8s
