---
- name: Get microk8s cluster joining link from master node
  hosts: localhost
  gather_facts: no
  tasks:

  - name: >
      Get the command to join.
      Create a new token for an hour
    shell: "microk8s add-node --token-ttl 3600 | awk 'NR==2'"
    register: run_from_worker

  - name: Set fact for the command
    set_fact:
      become_a_node_command: "{{ run_from_worker.stdout }}"

- name: Install microk8s on CentOS
  hosts: linux
  become: yes
  tasks:

  - name: Install EPEL packages
    yum:
      name: epel-release
      state: present

  - name: Install snapd using yum
    yum:
      name: snapd
      state: latest

  - name: Enable snap communication socket
    command: systemctl enable --now snapd.socket

  - name: Create a sym link if not exist
    file:
      src: /var/lib/snapd/snap
      dest: /snap
      state: link

  - name: Install Microk8s
    community.general.snap:
      name: microk8s
      state: present
      classic: yes

  - name: Join as worker of the k8s cluster
    shell: "snap run {{ hostvars['localhost']['become_a_node_command'] }} --worker"
...
